#!/bin/bash

# Variables.
SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DIR="$(dirname "$SCRIPTS_DIR")"
CLASSPATH=.:$DIR/vendor/junit-4.10.jar:$DIR/build

# Cleaning.
[ -d $DIR/build ] || mkdir $DIR/build
rm -rf $DIR/build/*

# Compiling.
javac -cp $CLASSPATH -d $DIR/build $DIR/*/memdb/*.java
javac -cp $CLASSPATH -d $DIR/build $DIR/examples/*.java

# Running.
java -cp $CLASSPATH PostsExample